### ISSUE TITLE
God i love cloud2butt Until it fucks up your code

### ISSUE THREAD

**Issue by fennectech** [sainitishkumar/covid-19#1]
https://github.com/sainitishkumar/covid-19/blob/master/all.html
Line 63 ;)

**Comment by sainitishkumar** [comment]
That's why I was using local files.

**Comment by fennectech** [comment]
Have fun :).  I found lots and lots of “buttflare” in search and was making issues on active codebases     After i got got by it

**Comment by sainitishkumar** [comment]
Neat. Keep going.
